Employees/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import login_view, home, AccountCreateView, AccountListView, AccountListJson, AccountUpdateView, \
    RequestCreateView, RequestUpdateView, RequestListView, RequestListJson, UpdateEmployee, RequestStatus

app_name = 'accounts'

urlpatterns = [
    # login and logout Urls
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # home url
    path('', home, name='home'),
    # Manager Urls
    path('employees/add/', AccountCreateView.as_view(), name='account_add'),
    path('employees/update/<int:pk>/', AccountUpdateView.as_view(), name='account_update'),
    path('employees/', AccountListView.as_view(), name='account_list'),
    path('employees/data/', AccountListJson.as_view(), name='account_list_data'),
    path('requests/<int:pk>/', RequestStatus.as_view(), name='request_status'),

    # Employee Url
    path('requests/add/', RequestCreateView.as_view(), name='request_add'),
    path('requests/update/<int:pk>/', RequestUpdateView.as_view(), name='request_update'),
    path('requests/', RequestListView.as_view(), name='request_list'),
    path('requests/data/', RequestListJson.as_view(), name='request_list_data'),


    # To edit your account
    path('update-info/', UpdateEmployee.as_view(), name='update-info'),
]

templates/account_manage/form.html
{% extends 'base.html' %}
{% load static widget_tweaks %}

{% block body %}
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>Add Employee</h2>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="body">
                            <h2 class="card-inside-title">Basic Info</h2>
                            {% if form.errors %}
                                <div class="alert bg-red alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                            aria-hidden="true">×</span></button>
                                    {{ form.errors }}
                                </div>
                            {% endif %}
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row clearfix">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.username type="text" class="form-control" placeholder="Username" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.email type="text" class="form-control" placeholder="Email" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.first_name type="text" class="form-control" placeholder="First Name" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.last_name type="text" class="form-control" placeholder="Last Name" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.password1 class="form-control" placeholder="Password" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.password2 class="form-control" placeholder="Confirm Password" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        {% render_field form.country class="form-control show-tick" %}
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.address type="text" class="form-control" placeholder="Address" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.phone type="text" class="form-control" placeholder="Phone" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        {% render_field form.gender class="form-control show-tick" %}
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line">
                                                {% render_field form.image class="form-control" placeholder="image" %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <div class="form-line" id="bs_datepicker_container">
                                                {% render_field form.birth_date class="form-control" placeholder="Birth Date" %}
                                            </div>
                                        </div>
                                    </div>
                                    {% if request.path != '/update-info/' %}
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                {% render_field form.is_active type="checkbox" id="basic_checkbox_1" %}
                                                <label for="basic_checkbox_1">Active</label>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                {% render_field form.type class="form-control show-tick"%}
                                            </div>
                                        </div>
                                    {% endif %}

                                </div>
                                <div class="row clearfix">
                                    <div style="float: right;margin-right: 15px;">
                                        <input type="submit" class="btn bg-red btn-block btn-lg waves-effect"
                                               value="Save">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block extra_script %}
    <script>
        $(function () {
            //Bootstrap datepicker plugin
            $('#bs_datepicker_container input').datepicker({
                autoclose: true,
                container: '#bs_datepicker_container'
            });
        })
    </script>
{% endblock %}

templates/account_manage/list.html
{% extends 'base.html' %}
{% load static i18n %}
{% block extra_head %}
    {% include 'datatable_head.html' %}
{% endblock %}
{% block body %}
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>
                    Employees
                </h2>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="body">
                            <div class="table-responsive">
                                <table id="example1"
                                       class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                    <tr>
                                        <th>{% trans 'No' %}</th>
                                        <th>#</th>
                                        <th>{% trans 'Username' %}</th>
                                        <th>{% trans 'Email' %}</th>
                                        <th>{% trans 'Name' %}</th>
                                        <th>{% trans 'Birth Date' %}</th>
                                        <th>{% trans 'Active' %}</th>
                                        <th>{% trans 'Profile Image' %}</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>
                                    <tfoot>
                                    <tr>
                                        <th>{% trans 'No' %}</th>
                                        <th>#</th>
                                        <th>{% trans 'Username' %}</th>
                                        <th>{% trans 'Email' %}</th>
                                        <th>{% trans 'Name' %}</th>
                                        <th>{% trans 'Birth Date' %}</th>
                                        <th>{% trans 'Active' %}</th>
                                        <th>{% trans 'Profile Image' %}</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}
{% block extra_script %}
    {% include 'datatable_script.html' %}
    <script>
        const link = '/employees/update/';
        {# for num_render function in AdminLte/datatable_scripts.html #}
        const addLink = '{% url 'accounts:account_add' %}';
        {# for addBtn function in AdminLte/datatable_scripts.html #}
        $(document).ready(function () {
            $('#example1').dataTable({
                initComplete: function () {
                    this.api().columns(6).every(function () {
                        var column = this;
                        var select = $('<select style="margin-left: 15px"><option value=""></option></select>')
                            .appendTo($(column.header()))
                            .on('change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
                                column.search(val).draw();
                            });
                        let a = '{% trans 'Active' %}'
                        select.append('<option value="True">' + a + '</option>')
                        a = '{% trans 'Inactive' %}'
                        select.append('<option value="False">' + a + '</option>')
                    });
                },
                responsive: true,
                autoWidth: true,
                lengthMenu: lengthMenu,
                order: [],
                dom: 'Bfrtip',
                buttons: buttons, {# global variable define in AdminLte/datatable_scripts.html #}
                language: dt_language, {# global variable defined in AdminLte/datatable_scripts.html #}
                columns: [
                    {data: 0, render: num_render}, {# global function define in AdminLte/datatable_scripts.html #}
                    {data: 0, render: checkbox_render}, {# global function define in AdminLte/datatable_scripts.html #}
                    {data: 1},
                    {data: 2},
                    {data: 3},
                    {data: 4},
                    {
                        data: 5,
                        render: true_false_render
                    },
                    {data: 6, render: img_render}, {# global function define in AdminLte/datatable_scripts.html #}
                ],
                columnDefs: [
                    {
                        targets: [2],
                        className: 'align-middle text-center',
                        orderable: true,
                        searchable: true
                    },
                    {
                        targets: [0, 1, 3, 4, 5, 6, 7],
                        className: 'align-middle text-center',
                        orderable: false,
                        searchable: false
                    }
                ],
                searching: true,
                processing: true,
                serverSide: true,
                stateSave: false,
                ajax: {
                    'url': '{% url "accounts:account_list_data" %}',
                    'data': function (data) {
                    }
                }
            });
        });
    </script>
{% endblock %}