Employees/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import login_view, home, AccountCreateView, AccountListView, AccountListJson, AccountUpdateView, \
    RequestCreateView, RequestUpdateView, RequestListView, RequestListJson, UpdateEmployee, RequestStatus

app_name = 'accounts'

urlpatterns = [
    # login and logout Urls
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # home url
    path('', home, name='home'),
    # Manager Urls
    path('employees/add/', AccountCreateView.as_view(), name='account_add'),
    path('employees/update/<int:pk>/', AccountUpdateView.as_view(), name='account_update'),
    path('employees/', AccountListView.as_view(), name='account_list'),
    path('employees/data/', AccountListJson.as_view(), name='account_list_data'),
    path('requests/<int:pk>/', RequestStatus.as_view(), name='request_status'),

    # Employee Url
    path('requests/add/', RequestCreateView.as_view(), name='request_add'),
    path('requests/update/<int:pk>/', RequestUpdateView.as_view(), name='request_update'),
    path('requests/', RequestListView.as_view(), name='request_list'),
    path('requests/data/', RequestListJson.as_view(), name='request_list_data'),


    # To edit your account
    path('update-info/', UpdateEmployee.as_view(), name='update-info'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
    {% block extra_head %}

    {% endblock %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {% include 'header.html' %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {% block body %}
                
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'scripts.html' %}
    {% block extra_script %}

    {% endblock %}
</body>
</html>

templates/datatable_head.html
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.23/af-2.3.5/b-1.6.5/b-colvis-1.6.5/b-flash-1.6.5/b-html5-1.6.5/b-print-1.6.5/cr-1.5.3/fc-3.3.2/fh-3.1.8/kt-2.6.1/r-2.2.7/rg-1.1.2/rr-1.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.1/datatables.min.css"/>

templates/datatable_script.html
{% load static i18n %}

<form id="DelForm" method="post">
    {% csrf_token %}
</form>
<div class="modal fade" id="modal-danger">
    <div class="modal-dialog">
        <div class="modal-content bg-danger">
            <div class="modal-header">
                <h4 class="modal-title">{% trans 'Delete' %}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="modalBody"></p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-outline-light"
                        data-dismiss="modal">{% trans 'Close' %}</button>
                <button type="button" class="btn btn-outline-light" onclick="delBtn()">{% trans 'Delete' %}</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript"
        src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.23/af-2.3.5/b-1.6.5/b-colvis-1.6.5/b-flash-1.6.5/b-html5-1.6.5/b-print-1.6.5/cr-1.5.3/fc-3.3.2/fh-3.1.8/kt-2.6.1/r-2.2.7/rg-1.1.2/rr-1.2.7/sc-2.0.3/sb-1.0.1/sp-1.2.2/sl-1.3.1/datatables.min.js"></script>
<style>
    .visable {
        position: inherit !important;
        left: 0 !important;
        opacity: 1 !important;
    }
</style>
<script>

    const dt_language = {
        "emptyTable": "{% trans "No data available in table" %}",
        "info": "{% trans "Showing _START_ to _END_ of _TOTAL_ entries" %}",
        "infoEmpty": "{% trans "Showing 0 to 0 of 0 entries" %}",
        "infoFiltered": "{% trans "(filtered from _MAX_ total entries)" %}",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "{% trans "Show _MENU_ entries" %}",
        "loadingRecords": "{% trans "Loading..." %}",
        "processing": "{% trans "Processing..." %}",
        "search": "{% trans "Search:" %}",
        "zeroRecords": "{% trans "No matching records found" %}",
        "paginate": {
            "first": "{% trans "First" %}",
            "last": "{% trans "Last" %}",
            "next": "{% trans "Next" %}",
            "previous": "{% trans "Previous" %}"
        },
        "aria": {
            "sortAscending": "{% trans ": activate to sort column ascending" %}",
            "sortDescending": "{% trans ": activate to sort column descending" %}"
        },
    };
    const lengthMenu = [
        [10, 25, 50, 100, -1],
        ['10', '25', '50', '100', 'Show all']
    ];
    const buttons = [
        'pageLength',
        {
            text: '{% trans 'Add' %}',
            className: 'btn btn-success waves-effect',
            action: addBtn
        },
        {
            text: '{% trans 'Select All' %}',
            className: 'btn btn-warning',
            action: selectAll
        },
        {
            text: '{% trans 'Delete' %}',
            className: 'btn btn-danger',
            action: function (e, dt, node, config) {
                const selected = new Array();
                $("#example1 input[type=checkbox]:checked").each(function () {
                    selected.push(this.value);
                });
                if (selected.length > 0) {
                    document.getElementById('modalBody').innerText = '{% trans 'you will delete ' %}' + selected.length
                    $('#modal-danger').modal('show');
                } else {
                    Toast.fire({
                        icon: 'error',
                        text: '{% trans 'You Must Check Rows' %}'
                    })
                }
            }
        },
        {
            extend: 'copy',
            text: '{% trans 'Copy' %}'
        },
        {
            extend: 'csv',
            text: '{% trans 'CSV' %}'
        },
        {
            extend: 'excel',
            text: '{% trans 'Excel' %}'
        },

        {
            extend: 'print',
            text: '{% trans 'Print' %}',
            title: '{{site_info.name}}',
            autoPrint: false,
            repeatingHead: {
                logo: 'assets/dist/img/report-logo.png',
                logoPosition: 'right',
                logoStyle: '',
                title: 'test'
            },
            exportOptions: {
                columns: ':visible',
                stripHtml: false
            },
            customize: function (win) {
                $(win.document.body)
                    .css('font-size', '10pt')
                    .prepend(
                        '<img src="{{request.scheme}}://{{request.META.HTTP_HOST}}{{ site_info.logo.url }}" style="position:absolute; top:20%; left:25%;max-height: 500px;opacity: 0.5;" />'
                    );

                $(win.document.body).find('table')
                    .addClass('compact')
                    .css('font-size', 'inherit');
            }
        },
        {
            extend: 'colvis',
            text: '{% trans 'Column Visibility' %}'
        }
    ]


    let flag = true

    function selectAll(e, dt, node, config) {
        $("#example1 input[type=checkbox]").each(function () {
            if (flag) {
                $(this).prop('checked', true);
            } else {
                $(this).prop('checked', false);
            }
        });
        if (flag) {
            flag = false
        } else {
            flag = true
        }
    }

    function delBtn() {
        const selected = new Array();
        $("#example1 input[type=checkbox]:checked").each(function () {
            selected.push(this.value);
        });
        document.getElementById('DelForm').innerHTML += '<input type="hidden" name="deleteIds" value="' + selected + '">';
        document.getElementById('DelForm').submit();
    }


    function addBtn(e, dt, node, config) {
        document.location.href = addLink;
    }

    function long_render(data, type, row, meta) {
        if (data.length > 20)
            return data.substring(0, 20) + ' ... ';
        return data;
    }


    function true_false_render(data, type, row, meta) {
        if (data == 'True') {
            return '<i style="color: #007fcc;font-size: 20px" class="fas fa-check"></i>'
        } else {
            return '<i style="color: red;font-size: 20px" class="fas fa-times"></i>'
        }

    }

    function img_render(data, type, row, meta) {
        return '<img style="max-height: 50px" src="' + data + '" >'
    }

    function checkbox_render(data, type, row, meta) {
        return '<input class="visable" type="checkbox" value="' + data + '" >'
    }

    function num_render(data, type, row, meta) {
        var num = meta.row + meta.settings._iDisplayStart + 1;
        return '<a href="' + link + data + '">' + num + '</a>'
    }

</script>

templates/head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<title>Expense Web App</title>
<!-- Favicon-->
<link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet"
      type="text/css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

<!-- Bootstrap Core Css -->
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.10.0/dist/css/bootstrap-select.min.css">


<!-- Waves Effect Css -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/node-waves/0.7.5/waves.min.css" rel="stylesheet"/>

<!-- Animation Css -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.0/animate.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
<link href="{% static 'css/themes/all-themes.css' %}" rel="stylesheet">

templates/header.html
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>
<!-- #END# Page Loader -->
<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->

<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse"
               data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="{% url 'accounts:home' %}">Expense Application</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">


                <li>
                    <a href="{% url 'accounts:logout' %}">
                        <i class="material-icons">input</i>
                    </a>
                </li>


            </ul>
        </div>
    </div>
</nav>
<!-- #Top Bar -->
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="image">
                <img src="{{ user.image.url }}" width="48" height="48" alt="User"/>
            </div>
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true"
                     aria-expanded="false">{{ user.first_name }} {{ user.last_name }}</div>
                <div class="email">{{ user.email }}</div>

            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">MAIN NAVIGATION</li>
                <li>
                    <a href="{% url 'accounts:home' %}">
                        <i class="material-icons">home</i>
                        <span>Home</span>
                    </a>
                </li>
                {% if user.type == user.MANAGER %}
                    <li>
                        <a class="menu-toggle waves-effect waves-block">

                            <i class="material-icons">supervisor_account</i>
                            <span>Co-ordinator</span>
                        </a>
                        <ul class="ml-menu">
                            <li>

                                <a class="waves-effect waves-block" href="{% url 'accounts:account_add' %}"
                                   class=" waves-effect waves-block">
                                    Add Coordinator</a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:account_list' %}" class=" waves-effect waves-block">
                                    Coordinator List</a>
                            </li>
                        </ul>
                    </li>
                {% endif %}

                <li>
                    <a class="menu-toggle waves-effect waves-block">

                        <i class="material-icons">assignment</i>
                        <span>Expense Requests</span>
                    </a>
                    <ul class="ml-menu">
                        {% if user.type == user.EMPLOYEE %}
                            <li>
                                <a class="waves-effect waves-block" href="{% url 'accounts:request_add' %}"
                                   class=" waves-effect waves-block">
                                    Add Request</a>
                            </li>
                        {% endif %}
                        <li>
                            <a href="{% url 'accounts:request_list' %}" class=" waves-effect waves-block">
                                Request List</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'accounts:update-info' %}">
                        <i class="material-icons">mode_edit</i>
                        <span>Edit Your Info</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; Ziyafat1446 <a href="javascript:void(0);"></a>.
            </div>
            <div class="version">
                <b>Husain Suksar - Nairobi Jamea</b>
            </div>
        </div>
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->

</section>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block extra_script %}
    <script src="{% static 'js/pages/index.js' %}"></script>

{% endblock %}
{% block body %}
    <section class="content">
        <div class="container-fluid">
            <script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2/webcomponents-loader.min.js"></script>

            <!-- Load the element definition -->
            <script type="module" src="https://cdn.jsdelivr.net/gh/zerodevx/zero-md@1/src/zero-md.min.js"></script>

            <!-- Simply set the `src` attribute to your MD file and win -->
            <zero-md src="{% static 'README.md' %}"></zero-md>

        </div>
    </section>
    <!-- Lightweight client-side loader that feature-detects and load polyfills only when necessary -->


{% endblock %}

templates/scripts.html
{% load static %}
<!-- Jquery Core Js -->
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<!-- Select Plugin Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>

<!-- Slimscroll Plugin Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js"></script>

<!-- Waves Effect Plugin Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/node-waves/0.7.5/waves.min.js"></script>

<!-- Jquery CountTo Plugin Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-countto/1.2.0/jquery.countTo.min.js"></script>

<!-- Morris Plugin Js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.0/morris.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script><!-- Custom Js -->
<script src="{% static 'js/admin.js' %}"></script>